<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;
use AppBundle\Entity\Company;
use \Doctrine\ORM\EntityRepository;
use Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException;

/**
 * CompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyRepository extends EntityRepository
{
    /**
     * Returns company by username.
     * @param string $username
     * @return Company
     * */
    public function findOneByUsername($username)
    {
        /** @var User $user */
        $user = $this->getEntityManager()->getRepository('AppBundle:User')
            ->findOneValidBy(['username' => $username]);

        /** @var Company $company */
        $company = $user->getCompany();

        if (!$company) {
            throw new AccessDeniedHttpException('Invalid user');
        }

        return $company;
    }
}
