<?php

namespace AppBundle\Repository;

use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\EntityRepository;

/**
 * DeviceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeviceRepository extends EntityRepository
{
    /**
     * Filter user Repository.
     * @param string $search
     * @param string $sortField
     * @param string $sortDirection
     * @return QueryBuilder
     * */
    public function findAllQueryBuilder($search = '', $sortField = 'id', $sortDirection = 'DESC')
    {
        $queryBuilder = $this->createQueryBuilder('d');

        $queryBuilder
            ->leftJoin('d.user', 'u')
        ;

        if ( !empty($search) ) {
            $availableFieldsForSearch = ['d.uuid', 'd.os', 'u.first_name', 'u.last_name', 'u.username', 'u.email'];

            foreach ($availableFieldsForSearch as $index => $field) {
                $where = $field.' LIKE :search';

                if (0 === $index) {
                    $queryBuilder->andWhere($where);
                } else {
                    $queryBuilder->orWhere($where);
                }
            }

            $queryBuilder
                ->setParameter('search', '%'.$search.'%')
            ;
        }

        return $queryBuilder->orderBy('d.' . $sortField, $sortDirection);
    }
}
